#!/usr/bin/python
###########################################################################
# Application:  is_it
# Function:     wrapper/qualifier for crontab entries,
#               tests for date conditions like "first Monday"
#               and returns exit status
###########################################################################
#load the required modules
import sys, string, calendar, time, datetime

def main():
    """ main entry point; only called if __main__ """
    
    global weekday_strings, month_strings, count_strings
    weekday_strings = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
    # blank [0] entry lets us count up from 1
    month_strings = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    count_strings = ["", "first", "second", "third", "fourth", "fifth", "last"]
    
    if len(sys.argv) < 5: usage()
    
    # get args crudely
    verbose = False
    testing = False
    foo = sys.argv
    for i in range(1,len(sys.argv)):
        if sys.argv[i] == "-h" or sys.argv[i] == "--help":
            usage()
        if sys.argv[i] == "-c" or sys.argv[i] == "--count":
            count = sys.argv[i+1]
            continue
        if sys.argv[i] == "-w" or sys.argv[i] == "--weekday":
            weekday = sys.argv[i+1]
            continue
        if sys.argv[i] == "-v" or sys.argv[i] == "--verbose":
            verbose = True
            continue
        if sys.argv[i] == "-t" or sys.argv[i] == "--test":
            testing = True
            test_today = sys.argv[i+1]
            continue
    # what day is it now?
    if testing == True:
        ttd = []
        for z in test_today.split("-"): ttd.append(int(z))
        now = datetime.datetime(ttd[0],ttd[1],ttd[2])
    else:
        now = datetime.datetime.now()
    this_year = now.year
    this_month = now.month
    this_day = now.day
    #this_weekday = ((now.weekday()+9)%7) # hinky math converts datetime's weekday 0-6 integer range of monday-sunday to the cron standard range of sunday-monday. good times.
    this_weekday = (now.weekday()+1)%7
    days_in_month = days_this_month(this_year,this_month)
    
    # parse/check args
    if "-" in count:
        # it's a range
        counts = count.split("-")
        for i in range(0,2):
            if len(counts)!=2 or counts[i] == "": usage("invalid count range")
            counts[i] = get_count(counts[i], now)
        if counts[1] < counts[0]:
            print "counts range must be increasing, if you're looping use a comma separated list"
            usage()
        for c in counts:
            if c < 1 or c > 6: usage("invalid count value")
        counts = range(counts[0],counts[1]+1)
    elif "," in count:
        # it's a list
        counts = count.split(",")
        for i in range(0,len(counts)):
            if counts[i] == "": usage("invalid count range")
            counts[i] = get_count(counts[i],now)
        counts.sort()
    else: counts = [get_count(count, now)] # it's a single value
    
    
    if "-" in weekday:
        # it's a range
        weekdays = weekday.split("-")
        for i in range(0,2):
            if len(weekdays)!=2 or weekdays[i] == "": usage("invalid weekday range")
            weekdays[i] = get_weekday(weekdays[i])
        if weekdays[1] < weekdays[0]:
                print "weekdays range must be increasing, if you're looping use a comma separated list"
                usage()
        for d in weekdays:
            if d > 7: usage("invalid weekday value")
        
        weekdays = range(weekdays[0],weekdays[1]+1)
    elif "," in weekday:
        # it's a list
        weekdays = weekday.split(",")
        for i in range(0,len(weekdays)):
            if weekdays[i] == "": usage("invalid weekday range")
            weekdays[i] = get_weekday(weekdays[i])
        weekdays.sort()
    else: weekdays = [get_weekday(weekday)] # it's a single value
            

    # walk a nested loop of the argument conditions and see if any apply
    for c in counts:
        for w in weekdays:
            # is today even the weekday we're looking for?
            if w != this_weekday:
                nope(c,w,this_month,verbose)
                break
            # we're looking for the last weekday
            if c == 6:
                if this_day > days_in_month-7:
                    yep(c,w,this_month,verbose)
            #otherwise, is this the c'th weekday 'w' of the month?
            else:
                this_week = week_of_month(now)
                if c == this_week:
                    yep(c,w,this_month,verbose)
                
    if verbose == True: print "no conditions matched"
    sys.exit(1)
            
    
def nope(c,w,m,verbose):
    if verbose == True:
        print "This is not the %s %s in %s" % (count_strings[c], weekday_strings[w], month_strings[m])

def yep(c,w,m,verbose):
    if verbose == True:
        print "This is the %s %s in %s" % (count_strings[c], weekday_strings[w], month_strings[m])
        print "conditions match"
    sys.exit(0)

def usage(doh=""):
    if doh != "": print "%s\n" % doh
    print "\nUsage: is_it -c count -w weekday [-v] [-t YYYYMMDD] [-h]"
    print "Test whether this is the \"c\'th\" weekday \"w\" of the month.\n"
    print "\t-c, --count \trecurrence count of the month e.g. \"f\" or \"first\",\n\t\t\t\"l\" or \"last\", 1,2,3,4,5"
    print "\t\t\tmultiple entries can be listed as a sequential range\n\t\t\te.g. 1-3 or a non-spaced comma separated list e.g. 2,4"
    print "\t-w, --weekday \tday of the week e.g. 0 to 6 (Sunday to Saturday),\n\t\t\t\"Mo,\" \"Mon,\" \"Monday\" (case insensitive)"
    print "\t\t\tmultiple entries can be listed as a sequential range\n\t\t\te.g. tue-thu or a non-spaced comma separated list e.g. mo,we"
    print "\t-v, --verbose  \techos output e.g \"it is not the last thursday\n\t\t\tof the month\" (default is silent)"
    print "\t-t, --test  \tpretends today is YYYY-MM-DD for testing purposes"
    print "\t-h, --help \tdisplays this help and exit\n"
    print "Exit status:"
    print "\t0\tdate test is positive"
    print "\t1\tdate test is negative or is_it otherwise failed"
    sys.exit(1)

def get_weekday(weekday):
    if "su" in weekday.lower(): return 0
    elif "mo" in weekday.lower(): return 1
    elif "tu" in weekday.lower(): return 2
    elif "we" in weekday.lower(): return 3
    elif "th" in weekday.lower(): return 4
    elif "fr" in weekday.lower(): return 5
    elif "sa" in weekday.lower(): return 6
    else: return int(weekday)

def get_count(count, now):
    if "f" in count.lower(): return 1
    elif "l" in count:
        #return int((days_this_month(now.year, now.month)+1)/7.0)
        return 6 # secret code for the last week
    else: return int(count)

def days_this_month(yr=datetime.datetime.now().year, mth=datetime.datetime.now().month):
    return calendar.monthrange(yr, mth)[1]

def week_of_month(dt):
    """Determines the week (number) of the month"""
    #Calendar object. 6 = Start on Sunday, 0 = Start on Monday
    cal_object = calendar.Calendar(6)
    month_calendar_dates = cal_object.itermonthdates(dt.year,dt.month)
    day_of_week = 1
    week_number = 1

    for day in month_calendar_dates:
        #add a week and reset day of week
        if day_of_week > 7:
            week_number += 1
            day_of_week = 1
        if dt.day == day.day:
            break
        else:
            day_of_week += 1

    return week_number

if __name__ == '__main__': main()
